// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZ40L8qFa7nwqb6GnpPFyHNey8HMImYtw',
    appId: '1:731466548662:web:3e1fbd5b24f5339f38ed17',
    messagingSenderId: '731466548662',
    projectId: 'blood-boon',
    authDomain: 'blood-boon.firebaseapp.com',
    storageBucket: 'blood-boon.appspot.com',
    measurementId: 'G-BD3ZWVKZH3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4r_hqlQA_lQ2Ikr7Ar8qPhU08aOx7vcI',
    appId: '1:731466548662:android:1f6ea1d45b5c796c38ed17',
    messagingSenderId: '731466548662',
    projectId: 'blood-boon',
    storageBucket: 'blood-boon.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAr0VH8TPa5xoeV5gj-kVTYfAh3zJ4yHVg',
    appId: '1:731466548662:ios:757968cea493e70638ed17',
    messagingSenderId: '731466548662',
    projectId: 'blood-boon',
    storageBucket: 'blood-boon.appspot.com',
    androidClientId: '731466548662-0rtr55feeb3gtdi9h253cmvp02tcmjok.apps.googleusercontent.com',
    iosClientId: '731466548662-2b076dmuq4v9nhilgopedkqelkbuan6b.apps.googleusercontent.com',
    iosBundleId: 'com.example.bloodBoon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAr0VH8TPa5xoeV5gj-kVTYfAh3zJ4yHVg',
    appId: '1:731466548662:ios:757968cea493e70638ed17',
    messagingSenderId: '731466548662',
    projectId: 'blood-boon',
    storageBucket: 'blood-boon.appspot.com',
    androidClientId: '731466548662-0rtr55feeb3gtdi9h253cmvp02tcmjok.apps.googleusercontent.com',
    iosClientId: '731466548662-2b076dmuq4v9nhilgopedkqelkbuan6b.apps.googleusercontent.com',
    iosBundleId: 'com.example.bloodBoon',
  );
}
